version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "python*"
      - dependency-name: "kubernetes*"
      - dependency-name: "sphinx*"